CREATE TABLE tb_users(
 usuario VARCHAR(255) PRIMARY KEY ,
 senha VARCHAR(255)
);

CREATE TABLE tb_alimentos
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome       VARCHAR(255)                            NOT NULL,
    quantidade VARCHAR(255),
    CONSTRAINT pk_tb_alimentos PRIMARY KEY (id)
);

CREATE TABLE tb_pessoa
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome               VARCHAR(255),
    altura             VARCHAR(255),
    idade              INTEGER,
    plano_alimentar_id BIGINT,
    CONSTRAINT pk_tb_pessoa PRIMARY KEY (id)
);

CREATE TABLE tb_plano_alimentar
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_plano_alimentar PRIMARY KEY (id)
);

CREATE TABLE tb_plano_alimentar_refeicao
(
    plano_alimentar_id BIGINT NOT NULL,
    refeicao_id        BIGINT NOT NULL
);

CREATE TABLE tb_refeicao
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_refeicoes VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_refeicao PRIMARY KEY (id)
);

CREATE TABLE tb_refeicao_alimentos
(
    refeicao_id  BIGINT NOT NULL,
    alimentos_id BIGINT NOT NULL
);

CREATE TABLE users
(
    usuario VARCHAR(255) NOT NULL,
    senha   VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (usuario)
);

ALTER TABLE tb_alimentos
    ADD CONSTRAINT uc_tb_alimentos_nome UNIQUE (nome);

ALTER TABLE tb_plano_alimentar
    ADD CONSTRAINT uc_tb_plano_alimentar_nome UNIQUE (nome);

ALTER TABLE tb_refeicao
    ADD CONSTRAINT uc_tb_refeicao_tiporefeicoes UNIQUE (tipo_refeicoes);

ALTER TABLE tb_pessoa
    ADD CONSTRAINT FK_TB_PESSOA_ON_PLANOALIMENTAR FOREIGN KEY (plano_alimentar_id) REFERENCES tb_plano_alimentar (id);

ALTER TABLE tb_plano_alimentar_refeicao
    ADD CONSTRAINT fk_tbplaaliref_on_plano_alimentar FOREIGN KEY (plano_alimentar_id) REFERENCES tb_plano_alimentar (id);

ALTER TABLE tb_plano_alimentar_refeicao
    ADD CONSTRAINT fk_tbplaaliref_on_refeicao FOREIGN KEY (refeicao_id) REFERENCES tb_refeicao (id);

ALTER TABLE tb_refeicao_alimentos
    ADD CONSTRAINT fk_tbrefali_on_alimentos FOREIGN KEY (alimentos_id) REFERENCES tb_alimentos (id);

ALTER TABLE tb_refeicao_alimentos
    ADD CONSTRAINT fk_tbrefali_on_refeicao FOREIGN KEY (refeicao_id) REFERENCES tb_refeicao (id);